# ### Specify the Docker image
image: mono

# ### Define variables
#
variables:
  GIT_STRATEGY: $STRATEGY
  BUILD_NUMBER: $CI_PIPELINE_ID  
  # 1) Name of directory where restore and build objects are stored.
  OBJECTS_DIRECTORY: 'obj'
  # 2) Name of directory used for keeping restored dependencies.
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  # 3) A relative path to the source code from project repository root.
  # NOTE: Please edit this path so it matches the structure of your project!
  SOURCE_CODE_PATH: '*/*/'

# ### Define stage list
#
# In this example there are only two stages.
# Initially, the project will be built and then tested.
stages:
  - build
  - test
#  - deploy

# ### Define global cache rule
#
# Before building the project, all dependencies (e.g. third-party NuGet packages)
# must be restored. Jobs on GitLab.com's Shared Runners are executed on autoscaled machines.
#
# Each machine is used only once (for security reasons) and after that is removed.
# This means that, before every job, a dependency restore must be performed
# because restored dependencies are removed along with machines. Fortunately,
# GitLab provides cache mechanism with the aim of keeping restored dependencies
# for other jobs.
#
# This example shows how to configure cache to pass over restored
# dependencies for re-use.
#
# With global cache rule, cached dependencies will be downloaded before every job
# and then unpacked to the paths as specified below.
cache:
  # Per-stage and per-branch caching.
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    # Specify three paths that should be cached:
    #
    # 1) Main JSON file holding information about package dependency tree, packages versions,
    # frameworks etc. It also holds information where to the dependencies were restored.
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
    # 2) Other NuGet and MSBuild related files. Also needed.
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    # 3) Path to the directory where restored dependencies are kept.
    - '$NUGET_PACKAGES_DIRECTORY'
    # 4) Test Libs
    #- 'Bierdeckel-Test/bin/Debug CI-CD/'
  #
  # 'pull-push' policy means that latest cache will be downloaded (if it exists)
  # before executing the job, and a newer version will be uploaded afterwards.
  # Such a setting saves time when there are no changes in referenced third-party
  # packages.
  #
  # For example, if you run a pipeline with changes in your code,
  # but with no changes within third-party packages which your project is using,
  # then project restore will happen quickly as all required dependencies
  # will already be there — unzipped from cache.

  # 'pull-push' policy is the default cache policy, you do not have to specify it explicitly.
  policy: pull-push

# ### Restore project dependencies
#
# NuGet packages by default are restored to '.nuget/packages' directory
# in the user's home directory. That directory is out of scope of GitLab caching.
#
# To get around this, a custom path can be specified using the '--packages <PATH>' option
# for 'dotnet restore' command. In this example, a temporary directory is created
# in the root of project repository, so its content can be cached.
#
# Learn more about GitLab cache: https://docs.gitlab.com/ee/ci/caching/index.html
before_script:
  - 'mono --version'
  - 'if [ ! -d $NUGET_PACKAGES_DIRECTORY ]; then mkdir $NUGET_PACKAGES_DIRECTORY; fi'
  - 'nuget restore -PackagesDirectory $NUGET_PACKAGES_DIRECTORY'

build_job:
  stage: build
  # ### Build all projects discovered from solution file.
  script:
    - 'msbuild -p:Configuration="TravisCI" -p:Platform="Any CPU" -p:PackageLocation="$NUGET_PACKAGES_DIRECTORY"'
     # -p:TargetFrameworkVersion=v4.7
     # -p:RestorePackages=false
  artifacts:
    paths:
      - 'CompuMaster.Test.TinyWebServerAdvanced/bin/Debug CI-CD/'
      - 'CompuMaster.Data/bin/Debug CI-CD/'
      - 'CompuMaster.Data.Controls/bin/Debug CI-CD/'
      - 'CompuMaster.Test.Tools.Data/bin/CI/'

test_job:
  stage: test
  # ### Run the tests
  before_script:
    - 'curl https://raw.githubusercontent.com/jochenwezel/nunit-transforms-to-junit-gitlab-compatible/master/nunit3-junit/nunit3-junit.xslt > nunit3-junit.xslt'
  script:
    - 'ls -la "./CompuMaster.Test.Tools.Data/bin/CI/"'
    - 'nuget install NUnit.Runners -Version 3.12.0 -OutputDirectory testrunner'
    - 'mono ./testrunner/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe "./CompuMaster.Test.Tools.Data/bin/CI/CompuMaster.Test.Tools.Data.dll" --result=TestResult.JUnit.xml\;transform=nunit3-junit.xslt --result=TestResult.xml'
  artifacts:
    when: always  # save test results even when the task fails
    expire_in: 1 month  # save gitlab server space, we copy the files we need to deploy folder later on
    paths:
      - './TestResult.xml'  # saving NUnit results
      - './TestResult.JUnit.xml'  # saving NUnit results as Jenkins JUnit XML
    reports:
      junit:
        - './TestResult.JUnit.xml'  # saving NUnit results as Jenkins JUnit XML
  dependencies:
    - build_job

