language: csharp
solution: CompuMaster.Data.VS2012.sln

mono:
  - latest

addons:
  apt:
    packages:
      - unixodbc
      - unixodbc-dev
      - libmyodbc
      - libmdbodbc1 
#dotnet: 
#  - 1.0.1
#  - 2.0.0-Preview1
#  - latest
#os: windows
dist: trusty
#sudo: required
#mono: none
before_install:
  - nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory testrunner
#  - sudo apt-get install nunit-console
install:
  - nuget restore CompuMaster.Data.VS2012.sln
script:
  - msbuild /p:Configuration=TravisCI /p:Platform="Any CPU" /p:PostBuildEvent="" CompuMaster.Data.VS2012.sln
after_script:
#  - ./testrunner/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./CompuMaster.Test.Tools.Data/bin/CompuMaster.Test.Tools.Data.dll
#  - nunit-console ./CompuMaster.Test.Tools.Data/bin/CompuMaster.Test.Tools.Data.dll