platform: Any CPU
configuration: AppVeyorCI

# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - install-packages

install:
#  - ps: 'Write-Host "Installing 2007 Office System Driver: Data Connectivity Components..."'
#  - ps: New-Item -ItemType Directory -Force -Path ".\install-packages"  
#  - ps: 'if (!(Test-Path "$env:APPVEYOR_BUILD_FOLDER\install-packages\AccessDatabaseEngine.exe")) { (New-Object Net.WebClient).DownloadFile("https://download.microsoft.com/download/3/5/C/35C84C36-661A-44E6-9324-8786B8DBE231/AccessDatabaseEngine.exe", "$env:APPVEYOR_BUILD_FOLDER\install-packages\AccessDatabaseEngine.exe") }'
#  - ps: .\install-packages\AccessDatabaseEngine.exe /quiet
#  - ps: 'Write-Host "OK" -foregroundcolor Green'
before_build:
  - nuget restore
